### ISSUE TITLE
V2 ideas (Optional)

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-spotify-playlist-maker-waldothedeveloper#1]
# Description
Congratulations on completing the project! Now that your project has reached v1 status, you may want to introduce some new features.

## Suggestions
- [ ] Improve the auth workflow. Right now, the token expires after 24 hours. You could improve the app so that it "refreshes" the token for the user, which would result in fewer login screens for the user and a better ux.
- [ ] Put in some logic that prevents the same song from ever appearing more than once until the user "clears their cache". Ensure the playlist is always at least 30 minutes.
- [x] Refactor your codebase. Did you "hack" something together in order to accomplish this on time? Go back and refactor it so that the code is clearer and more flexible.
- [x] Improve the UI. For example, add a logo, a background image, a color scheme, new fonts, or fancy animations. 
- [x] Make the app mobile-friendly.

**Comment by waldothedeveloper** [comment]
Can you take a look at this issue @scott-coates ?  

https://github.com/Scott-Coates-Org/solo-project-spotify-playlist-maker-waldothedeveloper/issues/28

**Comment by scott-coates** [comment]
Congrats on finishing the project. I will look at it this week and get back
to you. Great work.

**Comment by scott-coates** [comment]
Wow, great job! I love the design and the transitions!

I tested it and it worked, so I will go ahead and mark this project complete. What do you prefer to do next, keep working on v2, begin the medium project, something else?

**Comment by waldothedeveloper** [comment]
Hi there @scott-coates, thank you so much! I'm thrilled you liked it! I want to jump to the medium project, but there are a few things related to the UI/UX part (v2) that I feel can be improved just a little bit more. If that's ok with you, I can work on them for maybe a couple of more days, and then start the medium project.

Would you be able to give me a quick code review for this project? 
It's probably not the prettiest or most robust code I can feel proud of, but getting this technical feedback from you is extremely important for me. It doesn't need to be an in-depth review, just a few lines for me to think about what can be refactored for good. 

Again, super happy you liked it, and looking forward to hearing from you soon!
