### ISSUE TITLE
Test separate user in production

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-spotify-playlist-maker-waldothedeveloper#14]
# Description
Now that your Firebase project is live, let's test it with a different user. Because this is a hobby project, Spotify requires you to add users to test it first. I will share an SMX test Spotify account, that way you and I can both test your project before we wrap up v1.

## Requirements
- [x] Add the SMX test user.
  - [x] Click the Users and Access button.
![My_Dashboard___Spotify_for_Developers](https://user-images.githubusercontent.com/1829591/212419346-c40665b0-26be-4b95-9ca4-06613343fc82.png)
- [x] Click Add New User.
![image](https://user-images.githubusercontent.com/1829591/212420083-2e520079-483b-4e85-bf9b-c8788add714a.png)
  - [x] Enter `SMX Tester` for Name.
  - [x] Enter `scott@scott-coates.com` for Email.
![image](https://user-images.githubusercontent.com/1829591/212420343-5355cd84-82e0-453b-8d9c-22ad7bc647fe.png)
- [x] Open a new incognito browser session and visit your app, because this will allow you to test the new user without having to log out first. Test your app and ensure that it works for this user.
  - [x] Email: `scott@scott-coates.com`.
  - [x] Password: `SMXTester123`.
- [x] Send a DM to Scott Coates and have him test it. He will mark your project complete once it's verified to be working.

**Comment by scott-coates** [comment]
@waldothedeveloper Hey Waldo, I added this issue after you had already started, so it never made it in. I'm manually adding this issue to your repo. Great work so far!

**Comment by waldothedeveloper** [comment]
The testing account works as well!
