### ISSUE TITLE
Create UI layout

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-spotify-playlist-maker-waldothedeveloper#9]
# Description
Create the UI layout of the app.

![image](https://user-images.githubusercontent.com/1829591/208957619-8ebc5d5d-3260-4f83-8a14-8e138e5f1684.png)

## Requirements
- [x] When a user is **NOT** logged in, display the default hero section.
- [x] When a user is logged in, display the form for them to create their playlist.
![image](https://user-images.githubusercontent.com/1829591/208820294-f2ed422d-226f-4632-9109-0759fa161ad7.png)
- **Do NOT make the profile image appear yet, that will be in another task.**

**Comment by waldothedeveloper** [comment]
Hi @scott-coates, how are you? Hope you're doing well. 
The list of requirements for this issue mentions:

>  When a user is logged in, display the form for them to create their playlist.

I can't find an issue related to creating a mockup of the form for a logged-in user.
However, the ReadMe First issue
[https://github.com/Scott-Coates-Org/solo-project-spotify-playlist-maker-waldothedeveloper/issues/13](url)
contains the mockup of how the form should look like. 

Based on this observation:

- Should we include a picture of the mockup form in this issue, just like we see it in the ReadMe First issue?

Or
- Should we have a separate issue to tackle the form?

**Comment by scott-coates** [comment]
Hey @waldothedeveloper, good catch. Yeah, you can refer to that mockup for how the form should look. I'll fix on my end.
